Revert "qcacmn: discard IPA TX ring flush before RTPM suspend"
 * Avoid compile error:

../../../../../../kernel/xiaomi/alioth/drivers/staging/qca-wifi-host-cmn/dp/wifi3.0/dp_main.c:10576:13: error: use of undeclared identifier 'IPA_TCL_DATA_RING_IDX'
                        if (i == IPA_TCL_DATA_RING_IDX)
                                 ^
1 error generated.

This reverts commit 744bb4484b85bd587290bf7ae207e08dc9107f60.